[tool.poetry]
name = "dwavexp"
version = "0.1.0"
description = ""
authors = ["leakedweights <vkristof20@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wandb = "^0.16.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
